Question 1

Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

In [30]:
from array import *
def convert_list (array):
    list1=array.tolist()
    print(list1)
convert_list (array ('l', [12,23,34,56,89,74]))

[12, 23, 34, 56, 89, 74]


 Question 2 

Write a NumPy program to compute the sum of the diagonal element of a given array.


In [52]:
import numpy as np
diag_ele=np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(diag_ele)
sum_diag= np.trace(diag_ele)
print(sum_diag)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

In [65]:
import numpy as np
from array import *
diag_ele=np.array ([[1,2,3],[4,5,6],[7,8,9]])
list1= diag_ele.tolist()
print(list1)
fusion= np.concatenate(list1)
print(fusion)
for i,e in enumerate(fusion):
    if e>2:
        print(e , "is higher then 2")  

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1 2 3 4 5 6 7 8 9]
3 is higher then 2
4 is higher then 2
5 is higher then 2
6 is higher then 2
7 is higher then 2
8 is higher then 2
9 is higher then 2


Question 4

Given two arrays A&B having the same shape. 

The task is to apply addition by hand : C is the new array. 

In [89]:
A= np.array([1,5,8,6,4,5,8,7]).reshape(2,4)
B=np.array([2,5,6,4,8,9,3,1]).reshape(2,4)
print(A)
print(B)
C = [[0,0,0,0],[0,0,0,0]]
for i in range(len(A)):   
    for j in range(len(A[0])):
        C[i][j] = A[i][j] + B[i][j]
for new_array in C:
    print(new_array)

[[1 5 8 6]
 [4 5 8 7]]
[[2 5 6 4]
 [8 9 3 1]]
[3, 10, 14, 10]
[12, 14, 11, 8]


Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

In [98]:
sub = B - B.mean(axis=1, keepdims=True) #conserve les dimensions (keepdims)
print(sub)    

[[-2.25  0.75  1.75 -0.25]
 [ 2.75  3.75 -2.25 -4.25]]
